### ISSUE TITLE
optimizer conditional doesn't use tf.cond()

### ISSUE THREAD

**Issue by kdavis-mozilla** [mozilla/DeepSpeech#108]

**Comment by kdavis-mozilla** [comment]
@tilmankamp Want to take this? It should make the operator graph smaller by a factor of two.

**Comment by kdavis-mozilla** [comment]
@tilmankamp Just thinking out loud about this.

I'm not sure this is the right way to do this as `optimizer` is defined at graph creation time not graph execution time and it is defined to have two different values an `tf.train.AdamOptimizer` and  `None`. Thus there are two different graphs.

Doubling the graph size seems like such a high price to pay to do validation. I'm wondering if there is a better solution.

**Comment by Cwiiis** [comment]
Here's my (WIP) crack at this: https://github.com/Cwiiis/DeepSpeech/tree/validation-graph-duplication

Inspecting the graph in Tensorboard doesn't show a duplicated graph and the results using ldc93s1 appear to be correct. It'd be good to test this on a larger data-set to see if it makes any difference to performance (either speeding things up or allowing a larger batch_size due to a smaller graph).

**Comment by tilmankamp** [comment]
Just made you the owner of this.

**Comment by Cwiiis** [comment]
So I've implemented this in the above-mentioned branch (which needs some tidying, but is otherwise complete and, I think, correct) and I can confirm it does indeed have the effect on the graph that one would expect.

Unfortunately, it seems to have no effect at all on either speed or memory use. I suppose this makes sense if we were to assume that tf session runs are optimised to only include the parts of the graph that are depended upon.

I think the code like this (once tidied, at least) is a little more readable, so perhaps we want to include this after @tilmankamp's changes anyway. @kdavis-mozilla, what do you think?

**Comment by kdavis-mozilla** [comment]
@Cwiiis I haven't looked in detail at the code, I just ran it :-) So I'm not sure how easy it would be to integrate with @tilmankamp changes. 

Also, @tilmankamp has done a rather large re-organization so I think integration/merging will not be easy.

Maybe the first thing to do is to look at tensorboard's graph for @tilmankamp code, then see if this type of fix is still needed.

Also, I am wondering if this change is worth including as it seems, in direct opposition to everyone's expectations, it doesn't allow us to increase batch size.

**Comment by tilmankamp** [comment]
@Cwiiis Please comment on #176 once you verified success.

**Comment by Cwiiis** [comment]
Verified success;
Master: https://www.dropbox.com/s/mlir5523m84mw0d/graph-master.png?dl=0
#192: https://www.dropbox.com/s/h1v07npdepy4yyg/graph-no-duplication.png?dl=0
