### ISSUE TITLE
Running on RPi3 fails because of SparseToDense

### ISSUE THREAD

**Issue by lissyx** [mozilla/DeepSpeech#1095]
```
pi@raspberrypi:~/nc_r1.3 $ ./deepspeech ~/tmp/output_graph.pb ~/wav/LDC93S1.wav ~/tmp/alphabet.txt 
Invalid argument: No OpKernel was registered to support Op 'SparseToDense' with these attrs.  Registered devices: [CPU], Registered kernels:
  device='CPU'; T in [DT_STRING]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_STRING]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_BOOL]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_BOOL]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_FLOAT]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_FLOAT]; Tindices in [DT_INT32]
  device='CPU'; T in [DT_INT32]; Tindices in [DT_INT64]
  device='CPU'; T in [DT_INT32]; Tindices in [DT_INT32]

	 [[Node: SparseToDense = SparseToDense[T=DT_INT64, Tindices=DT_INT64, validate_indices=true](CTCBeamSearchDecoder, CTCBeamSearchDecoder:2, CTCBeamSearchDecoder:1, SparseToDense/default_value)]]
Segmentation fault
```

**Comment by lissyx** [comment]
We'll just have a trigger a new build once https://tools.taskcluster.net/task-group-inspector/#/Cl-jCpbdSxacYZjblrnEgQ is green.

**Comment by lissyx** [comment]
DeepSpeech build: https://tools.taskcluster.net/groups/USJfxXvPTImrAw45Ngrljg

**Comment by lissyx** [comment]
Shoud be good by now.

**Comment by maremoto** [comment]
Hello, 

I am trying to infer a custom trained model with native client in a Asus Thinkerboard, a card similar to raspberry with 32bit armv7l architecture.
I tried to compile from scratch, including tensorflow, but ended up with the same error than this issue is reporting (the SparseToDense one).

Then I tried your raspberry-ready compiled libraries downloaded from:
https://queue.taskcluster.net/v1/task/Wnpx0NPjS3G20t76jbl15Q/runs/0/artifacts/public/native_client.tar.xz

But unfortunately this new "Illegal instruction" error showed up: 

Thread 1 "deepspeech" received signal SIGILL, Illegal instruction.
0xb692de84 in tensorflow::(anonymous namespace)::GraphConstructor::TryImport() () from /home/ftx/fonotexto/herramientas/DeepSpeech/nativelibs_jmd/libdeepspeech.so

(NOTE: in my raspberry pi3 these libraries work fine).

So I would like to do a specific compilation for the Thinkerboard card, could you give me any hint to do that and skip the SparseToDense error? 

Thanks in advance,
Mar

**Comment by lissyx** [comment]
@maremoto Right, building yourself is the proper solution, but you need to document what you did. If you rebuilt yourself the proper way, you should not have had the `SparseToDense` issue. Besides, can we have this discussion on Discoures https://discourse.mozilla.org/c/deep-speech ? We want to use issues only for bugs / features.

**Comment by maremoto** [comment]
Hi,

Thanks for the quick response, yes I have added a comment at discourse.mozilla.org, sorry for the inconvenience, you can discard the post at github.

I will send you an email with the steps I followed ¿or shoud I post them at the forum?.

Thanks again,

Mar





    On Monday, March 5, 2018, 11:48:39 AM GMT+1, lissyx <notifications@github.com> wrote:  
 
 
@maremoto Right, building yourself is the proper solution, but you need to document what you did. If you rebuilt yourself the proper way, you should not have had the SparseToDense issue. Besides, can we have this discussion on Discoures https://discourse.mozilla.org/c/deep-speech ? We want to use issues only for bugs / features.
