### ISSUE TITLE
clients for Microsoft Windows

### ISSUE THREAD

**Issue by sanjayraojjn** [mozilla/DeepSpeech#1123]
For support and discussions, please use our [Discourse forums](https://discourse.mozilla.org/c/deep-speech).

is there any plan to have clients for windows ?

**Comment by kdavis-mozilla** [comment]
No immediate plans, but if there is sufficient demand we will.

**Comment by danielsjf** [comment]
You can already get it running on Windows Subsystem for Linux.

https://fotidim.com/deepspeech-on-windows-wsl-287cb27557d4

**Comment by Franck-Dernoncourt** [comment]
> No immediate plans, but if there is sufficient demand we will.

Where should we voice demand for it?

**Comment by ccoenen** [comment]
I'd like to chime in: how is demand measured? Do we just Thumbs-Up this ticket?

**Comment by lissyx** [comment]
@ccoenen That's one thing, It also depends on what value it brings to the project, and how much work it is. And we need someone that has time, as well. TensorFlow support for Windows has greatly improved since several releases, and we also have been able to move on several topics, so it might happen sonner or later. I'd like to hack that, but I have a few of more urgent things to complete on, but what would be nice is OpenCL + Windows. I spent quite some time hacking on the first part, and it's looking not too bad :)

**Comment by ccoenen** [comment]
:-)
