### ISSUE TITLE
Benchmark bandpass filter

### ISSUE THREAD

**Issue by kdavis-mozilla** [mozilla/DeepSpeech#1259]
Benchmark bandpass filter with band 200-3k 
```
sox input.wav -b 16 output.wav channels 1 rate 16k sinc 200-3k
```

**Comment by jageshmaharjan** [comment]
That's for Native American English speaker, right? 
Any benchmark bandpass for Mandrian (Chinese Language).

**Comment by kdavis-mozilla** [comment]
It's for any model we have, but initially, yes, American English. But we have not done this yet.

It would be, due to tonality, an interesting benchmark for Mandrian.

**Comment by 3mei** [comment]
Would it make sense to release a model trained on 8kHz audio instead? 16kHz sampling rate means that the highest audio frequency is 8kHz (Nyquist–Shannon sampling theorem). If the aim of the bandpass filter is to limit audio to the voice-frequency range, the 8kHz sampling rate (4kHz max audio frequency) already achieves that. Hence, its use in telephony. In the same vein, `16k sinc 200-3k` in the sox command above may as well be written `6k sinc 200-3k`. In the limited tests that I've done, using downsampled audio with a pre-trained model doesn't yield very good results, which makes sense, since the training is done at 16kHz.

If doable, a pre-trained 8kHz model would be super useful!

**Comment by kdavis-mozilla** [comment]
The motivation of this issue was to consider a bandpass filter as a simple defense against a [dolphin attack](https://dl.acm.org/citation.cfm?id=3134052). The idea of the issues was then to find the effect of such a bandpass on WER.

I don't know how well a pre-trained 8KHz model would perform.

**Comment by 3mei** [comment]
Interesting, thank you for the pointer! It would certainly depend on the application. Speech itself is usually confined to about 4kHz, so an 8kHz model should theoretically work. Singing on the other hand is a whole different beast. 

According to the linked paper, since a dolphin attack needs to be inaudible,
> Carrier Wave Frequency fc is the dominant factor that affects the attack success rate [and] the fc range within which recognition attacks are successful can be as wide as 20–42 kHz.

Even the lowest carrier frequency range (20kHz) reported in the paper should not be an issue because the sampling rate needed to capture that carrier frequency is 40kHz. At a 16kHz sampling rate, the maximum carrier frequency is exactly half, or 8kHz.

**Comment by kdavis-mozilla** [comment]
Not going to do for now.
