### ISSUE TITLE
Pretrained model on features

### ISSUE THREAD

**Issue by coco90417** [mozilla/DeepSpeech#1402]
Hey, 

I love this work! I have been trying to use your pre-trained model on my own project. However, I prefer not to use wav file, but some features from wav file that you have used in training your model. Could you please give me an example of: 1. what are the features that are used (an exemplary input file would be perfect) 2. command line or python/java code to execute your pre-trained model?

Keep up the great work, cheers,

Coco

**Comment by solomonope** [comment]
Hi,
 This video helped me get started https://www.youtube.com/watch?v=aUSyzNr6iK8&t=9s,  This is an example python code to use the model, https://github.com/mozilla/DeepSpeech/blob/master/native_client/python/client.py , There is also a lot of information on the project readme.

With respect to using wav files,  I think you have to use wave files, if your audio are not in wave files you can convert them using https://github.com/jiaaro/pydub it is a wrapper around ffmpeg.

I hope this helps

**Comment by reuben** [comment]
`client.py` (and `client.js`) are already a bit high level if you're interested in hacking on the model inputs. If you look at `deepspeech.cc` or `util/audio.py`, you'll see that the features the model takes as input are MFCC coefficients. You can compute them with the `python_speech_features` module or the intuitively named `c_speech_features` (which is what we use in `deepspeech.cc`). Hope this helps. I'm closing the issue since there's nothing actionable here and it's more of an open ended question. Feel free to reopen the discussion over on [Discourse](https://discourse.mozilla.org/c/deep-speech) if needed.
