### ISSUE TITLE
Rebuilding Binary issue

### ISSUE THREAD

**Issue by ZeeshanSultan** [mozilla/DeepSpeech#1424]
- **I have not written any custom code so far**:
- **using Linux Ubuntu 16.04**:
- **Python 3.5.2**: 
- **Memory 32 GB**:

![binary](https://user-images.githubusercontent.com/8667667/42129538-8212c3a6-7ce0-11e8-91cf-969eb93a24d4.jpg)

![binary2](https://user-images.githubusercontent.com/8667667/42129536-7a6611d0-7ce0-11e8-921c-652828b82bac.jpg)

**Comment by lissyx** [comment]
@ZeeshanSultan Thanks, but please avoid using pictures for this purpose: it makes your issue non-indexable and hard to read. Also, it's not a big with DeepSpeech, so it'd be better to be discussed on Discourse: https://discourse.mozilla.org/c/deep-speech

Since you rebuilt, you also need to document what you did exactly: this error is about a mismatch between the lm.binary file format.

**Comment by lissyx** [comment]
Invalid now anyway, since we reverted to the old language model.
