### ISSUE TITLE
Linking error while building deepspeech native_client

### ISSUE THREAD

**Issue by bhargav-ak** [mozilla/DeepSpeech#1504]
Hi I'm getting a linking error while building deepspeech native client.
Here's the output of the make command
```bash
~/Coder/nlp/DeepSpeech/native_client: make deepspeech                                                                                          
c++ -o deepspeech   `pkg-config --cflags sox` client.cc  -Wl,--no-as-needed -Wl,-rpath,\$ORIGIN -L/home/bhargav/Coder/nlp/tensorflow/bazel-bin/native_client  -ldeepspeech -ldeepspeech_utils  `pkg-config --libs sox`
/usr/bin/x86_64-linux-gnu-ld: cannot find -ldeepspeech_utils
collect2: error: ld returned 1 exit status
Makefile:22: recipe for target 'deepspeech' failed
make: *** [deepspeech] Error 1
```
I have done `pip install deepspeech` and the `libdeepspeech.so` and `libdeepspeech_utils.so` are present at `/home/bhargav/.local/lib/python2.7/site-packages/deepspeech/lib`

Here's my LD_LIBRARY_PATH 
```bash
~/Coder/nlp/DeepSpeech/native_client: echo $LD_LIBRARY_PATH                                             
:/home/bhargav/.local/lib/python2.7/site-packages/deepspeech/lib:/home/bhargav/.local/lib/python2.7/site-packages/deepspeech/lib:/home/bhargav/.local/lib
```

Here are all the commands I'm using [Deepspeech Builder ](https://github.com/bhargav-ak/_root/blob/master/sidekick/scripts/deepspeech-build.sh)

**Comment by lissyx** [comment]
This is not a bug, please take discussions to Discourse instead.

I see a lot of bad habits in your script:
 - why do you rebuild the python wheel ? just use official ones
 - why in general do you rebuild everything, what is wrong with our prebuilt binaries ?
 - since you rebuild everything, why do you use prebuild `libdeepspeech_utils.so` and not just build it at the same time ?
 - current master does not have `libdeepspeech_utils.so` anymore

Check the linker flags used when you issue `make deepspeech`: we default with a `-L` pointing to a tensorflow build tree: in your case `-L/home/bhargav/Coder/nlp/tensorflow/bazel-bin/native_client`. This is consistent with your `bazel build --config=monolithic -c opt --copt=-O3 --copt="-D_GLIBCXX_USE_CXX11_ABI=0" --copt=-fvisibility=hidden //native_client:libdeepspeech.so //native_client:generate_trie` which built no `libdeepspeech_utils.so`

To make the linker pick it, it's not enough to set `LD_LIBRARY_PATH`, you need to add `-L/home/bhargav/.local/lib/python2.7/site-packages/deepspeech/lib`, with `EXTRA_LDFLAGS=-L/home/bhargav/.local/lib/python2.7/site-packages/deepspeech/lib` on your `make` call.

**Comment by bhargav-ak** [comment]
@lissyx Thank you for pointing out the mistakes (fixed the script as well)
- I am rebuilding it to add AVX2 FMA compatibility.
- I pulled the latest master branch and successfully built the binary.

I am getting the `op type not registered Assert` error.  [ Issue 1486 ](https://github.com/mozilla/DeepSpeech/issues/1486) speaks of the same error:
- _This is because alpha 9 switched to the new, incompatible streaming model. Use Alpha 8. cc_ 
- _This error should only happen if you try to use binary version v0.2.0-alpha.9 with the v0.1.1 models_

**How do I workaround this error, which release should I be pulling to make it work with the v0.1.1 models ?** 

```bash
 ~/Coder/nlp/DeepSpeech/native_client: 
 ~/Coder/nlp/DeepSpeech/native_client: ./deepspeech --model ../../models/output_graph.pb  --alphabet ../../models/alphabet.txt --lm ../../models/lm.binary --trie ../../models/trie --audio ../../audio/bckp/8455-210777-0068.wav
TensorFlow: v1.6.0-rc1-1453-g8f1e480540
DeepSpeech: v0.2.0-alpha.6-0-ge20301a
Warning: reading entire model file into memory. Transform model file into an mmapped graph to reduce heap usage.
Not found: Op type not registered 'Assert' in binary running on Inspiron-3542. Make sure the Op and Kernel are registered in the binary running in this process.
Could not create model.
```

**Comment by lissyx** [comment]
Well, you wrote it yourself, use v0.2.0-alpha.8 :-)

**Comment by lissyx** [comment]
Thanks @bhargav-ak. I don't see lines with AVX2 and FMA enabled. The flags are here but on commented lines.

**Comment by bhargav-ak** [comment]
@lissyx Worked out very nice :) [Deepspeech Builder (Intel CPU, with AVX2 and FMA support)](https://raw.githubusercontent.com/bhargav-ak/_root/master/sidekick/scripts/deepspeech-build.sh)
```bash
 ~/Coder/nlp/DeepSpeech/native_client: ➦ cd47560 ●: ./deepspeech --model ../../models/output_graph.pb  --alphabet ../../models/alphabet.txt --lm ../../models/lm.binary --trie ../../models/trie --audio ../../audio/bckp/8455-210777-0068.wav -t
TensorFlow: v1.6.0-rc1-1453-g8f1e480540
DeepSpeech: v0.2.0-alpha.8-0-gcd47560
Warning: reading entire model file into memory. Transform model file into an mmapped graph to reduce heap usage.
your power is sufficient i said.
cpu_time_overall=15.44525 cpu_time_mfcc=0.00792 cpu_time_infer=15.43733
```
