### ISSUE TITLE
Invalid argument of "preprocess" in evaluate.py

### ISSUE THREAD

**Issue by zjysteven** [mozilla/DeepSpeech#1637]
Hi! I'm now trying to evaluate the pre-trained model by checking out its WER on LibriVox dataset. However, when using `evaluate.py` I found the following issue:

https://github.com/mozilla/DeepSpeech/blob/59a9dd96006995083da3cbe3f518a2a9a28d7f7b/evaluate.py#L101-L104

https://github.com/mozilla/DeepSpeech/blob/59a9dd96006995083da3cbe3f518a2a9a28d7f7b/util/preprocess.py#L31

As you can see, in `evaluate.py` the function doesn't include arguments `numcep` and `numcontext`, also `hdf5_dest_path` doesn't match `hdf5_cache_path`. Thus when running `evaluate.py` I got `InvalidArgument` and `missing required positional arguments` errors.

Just wondering if anyone else came across this problem or it is just I missed something.

**Comment by lissyx** [comment]
It's broken, I've ran into the same issues and forgot to file a bug. There are other things that requires fixing in this file :)

**Comment by zjysteven** [comment]
Thanks for the response! BTW, do you have any instructions on how to assign values for those two arguments `numcep` and `numcontext`? I'm new to speech recognition and don't know which values are appropriate. Any suggestions will be appreciated!

**Comment by kdavis-mozilla** [comment]
@reuben Just to make sure you got pinged

**Comment by lissyx** [comment]
> Thanks for the response! BTW, do you have any instructions on how to assign values for those two arguments numcep and numcontext? I'm new to speech recognition and don't know which values are appropriate. Any suggestions will be appreciated!

Sorry, I should have made it more clear: even once this is fixed, there are some issues left that I've identified a few days ago but we have not yet fixed all of it.

If you are brave enough, you can give it a try, `numcep` and `numcontext` matches the respective values for `n_input` and `n_context` in `DeepSpeech.py`. You are right that `hdf5_dest_path` should be changed into `hd5f_cache_path`, and you might want to use keyword arguments for everything: `csv_files`, `batch_size`, ... You'll have to pass also the alphabet (defined earlier in `evaluate.py`, just pass it).

And then you should run into shape issues that are very very close to what I fixed in #1615 #1616 :).

So if you want to do fix and then a PR you're welcome :)

**Comment by reuben** [comment]
I'm working on a fix for the shape thing (as well as the other errors), it's more complicated than I expected due to how evaluate.py handles its feeding differently, at some point we have to apply the windowing to each sample's features.

**Comment by lissyx** [comment]
@zjysteven The fix in PR https://github.com/mozilla/DeepSpeech/pull/1642 is perfect, it's working for me :-)

**Comment by zjysteven** [comment]
@lissyx @reuben Thanks for all your help and the update!
