### ISSUE TITLE
shape of features matrix when loading from a hdf5_cache_path produces error

### ISSUE THREAD

**Issue by bill-kalog** [mozilla/DeepSpeech#1738]
should when loading from a cache path have the `features[i]` matrix be reshaped to `np.reshape(features[i], [features_len[i] + 2 * numcontext, -1])` instead, since we have at the function`process_single_file()` `features_len = len(features) - 2 * numcontext` . At the moment it was failing for me and you can't load from a `hdf5_cache_path`

**Comment by reuben** [comment]
Did you change the code? Consumers of preprocessed features need to apply the striding windows before feeding into the model: https://github.com/mozilla/DeepSpeech/blob/f5d3dcdc62238db08e3fca4f25e899133a0f0466/util/feeding.py#L135-L144

**Comment by abhijeet3922** [comment]
I am finding the same issue. 

Exception in thread Thread-22:
Traceback (most recent call last):
  File "/home/abhijeet/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/abhijeet/anaconda3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/abhijeet/Desktop/dl_projects/DeepSpeech/util/feeding.py", line 143, in _populate_batch_queue
    (features.strides[0], features.strides[0], features.strides[1]),
IndexError: tuple index out of range

It has become pain to wait for pre-processing steps for each and every experiment.
How can I debug this ? Can someone check and verify. I pulled the latest version 0.4.0-alpha.0

**Comment by abhijeet3922** [comment]
Well,

I solved the issue. If anyone is getting error while using feature caching --train_cached_features_path data/ldc then change the below code
features.strides[0], features.strides[0], features.strides[1]
to
features.strides[0], features.strides[0], features.strides[0]

**Comment by reuben** [comment]
That does not look like a correct change and is probably just masking some underlying problem. Can you document exactly what you're doing when you get these errors?

**Comment by reuben** [comment]
It could just be that you're trying to load an older, incompatible HDF5 file. We changed the layout of stored features some time ago.

**Comment by abhijeet3922** [comment]
I am performing experiments on Voxforge dataset of 100 hours.
OS - Ubuntu 16
GTX Nvidia 1080Ti, I7 8700 Gen

I am running this command for training ASR model

./DeepSpeech.py --train_files voxforge/voxforge-train.csv --dev_files voxforge/voxforge-dev.csv --test_files voxforge/voxforge-test.csv --train_batch_size 64 --dev_batch_size 64 --train_batch_size 64 --epoch 25 --n_hidden 512 --validation_step 1 --learning_rate 0.0001 --dropout_rate 0.22 --summary_secs 300 --earlystop_nsteps 5 --lm_binary_path data/voxforge/lm.binary --lm_trie_path data/voxforge/trie --train_cached_features_path data/voxforge/vox-train --dev_cached_features_path data/voxforge/vox-dev 

I have given "--train_cached_features_path data/voxforge/vox-train" parameter so that from next experiments I have trained feature cached in hdf5 file. It takes some 5-7 minutes to preprocess voxforge train set.

But next time when I am running the above command to train (say with different params), it gives error.

File "/home/abhijeet/Desktop/dl_projects/DeepSpeech/util/feeding.py", line 143, in _populate_batch_queue
(features.strides[0], features.strides[0], features.strides[1]),
IndexError: tuple index out of range  

I thought features.strides[1] index is going out of range, So changed it to 0 and things worked for me in train and dev cached features.

Which version of hdf5 should be used ?
"h5cc -showconfig" command gives the following
General Information:
-------------------
                   HDF5 Version: 1.10.2

"dpkg -s libhdf5-dev" says
dpkg-query: package 'libhdf5-dev' is not installed and no information is available

Thanks

**Comment by kishorekolla** [comment]
I modified the code to below and it is working

```
  for i in range(len(features)):
                features[i] = np.reshape(features[i], (len(features[i]) // numcep,numcep))
```

**Comment by reuben** [comment]
@abhijeet3922 sorry for missing your message. Can you try this patch? 
[shape.diff.txt](https://github.com/mozilla/DeepSpeech/files/2836425/shape.diff.txt)
