### ISSUE TITLE
util/taskcluster.py should fetch deepspeech.h to complement libdeepspeech.so

### ISSUE THREAD

**Issue by davidrpiper** [mozilla/DeepSpeech#2214]
Hi all,

I've just started playing around with Deep Speech, and I notice that in the script to download pre-built binaries for the platform (util/taskcluster.py) does not fetch `deepspeech.h` to complement `libdeepspeech.so`.

I'm looking to create my own native client (in C++) and to do this you need both the shared library and the appropriate header file. A quick look in the `native_client` directory turns up what appears to be the correct header file (deepspeech.h), but I'm just wondering why this isn't fetched alongside `libdeepspeech.so` by default.

Thank you all for your amazing work!

**Comment by reuben** [comment]
Good point, we should package that with the native client package.

**Comment by lissyx** [comment]
> I'm looking to create my own native client (in C++) and to do this you need both the shared library and the appropriate header file. A quick look in the `native_client` directory turns up what appears to be the correct header file (deepspeech.h), but I'm just wondering why this isn't fetched alongside `libdeepspeech.so` by default.

Mostly because we never felt this was really needed. The tooling you refer to is usesul because prebuilt binaries can be non trivial to find and to us help also with CI.

Given the header is directly accessible from Github for downloading, easy to discover, and already here when you `git clone` we never considereed it would ne needed.

**Comment by davidrpiper** [comment]
Thank you both for the fast response - and fast implementation!
