### ISSUE TITLE
tensor dimension trained models

### ISSUE THREAD

**Issue by MikeLevene283** [mozilla/DeepSpeech#2301]
With the first DeepSpeech release v0.1.0 it was possible to directly access the trained model (output_graph.pb) for inference with a few lines of code (e.g. something along these lines
`graph = tf.get_default_graph()
  tf.import_graph_def(graph_def, name="deepspeech")
 input_node = graph.get_tensor_by_name('deepspeech/input_node:0')
 input_lengths = graph.get_tensor_by_name('deepspeech/input_lengths:0')
 output = graph.get_tensor_by_name('deepspeech/logits:0')`

For newer versions (e.g. v0.4.0) however this seems to be not possible anymore as the input_node has a fixed dimension (i.e. (1, 16, 19, 26)) compared to the dynamic size in v0.1.0 (i.e. (?,?,494)) which allowed to pass the entire sequence as one batch. How can one directly use the trained models for sequences of arbitrary length?

**Comment by reuben** [comment]
You'll have to re-export from the checkpoint with `--n_steps -1`, take a look at evaluate.py to see how the graph can then be used.

**Comment by MikeLevene283** [comment]
Thank you for the fast answer. Re-exporting from the checkpoint with `--n_steps -1` does the job. Is there any advantage of the provided models having a fixed batch size?

One additional problem occurs when using a version newer than 0.4.1. Directly loading the model with the code posted in the initial comment (i.e. using `tf.import_graph_def(...)`) causes following error:

> ValueError: NodeDef mentions attr 'feature_win_len' not in Op<name=NoOp; signature= -> >; NodeDef: {{node deepspeech/model_metadata}}. (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).

Is there any possibility of using the fixed graph directly for inference only without being required to build the graph first?

**Comment by reuben** [comment]
The reason why our inference graph only processes 16 time steps at a time is that we want to support streaming inference, and with a graph that takes the entire audio file at once that's not possible.

The import failure is due to a special metadata node that we put in the graph when saving. IIRC you can simply delete that node from the graph before calling import_graph_def with `del g['model_metadata']`. As you can see, what you're doing is not exactly a supported use case :P

> Is there any possibility of using the fixed graph directly for inference only without being required to build the graph first?

Of course, that's what our native clients are for!

**Comment by MikeLevene283** [comment]
Thanks a lot for your answer. I have one more question for this inference without building the graph.

>     Is there any possibility of using the fixed graph directly for inference only without being required to build the graph first?
> 
> Of course, that's what our native clients are for!

I am not quite sure how to do that. If I look into the evaluate.py or the DeepSpeech.py (i.e. do_single_file_inference) you always build the graph first by calling create_model before loading the checkpoint. Do you have any example how to just load the frozen graph and do inference? Loading the fixed graph with the few lines of code from the initial post works for v0.1.0 but for newer ones it results in a error regarding the LSTM layer

> tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'BlockLSTM'

**Comment by reuben** [comment]
We have all the steps documented in the README, eg. https://github.com/mozilla/DeepSpeech/blob/master/README.md#using-a-pre-trained-model

**Comment by MikeLevene283** [comment]
Sorry, but if I am not mistaken, the README just mentions how to do inference with the pre-trained model using the installed deepspeech package. I don't see any Python code to directly load the frozen graph and do inference (without building the graph and restoring the checkpoint)

**Comment by reuben** [comment]
Oh, so you want to use TensorFlow to directly load the exported graph? Then you'll have to use the checkpoint. Our pre-trained models are meant to be used with the native client or their bindings for Python/NodeJS/Rust/etc. Any direct manipulation should be done via the checkpoint rather than the exported model to avoid any weirdness (like the metadata node for example).

**Comment by MikeLevene283** [comment]
> Oh, so you want to use TensorFlow to directly load the exported graph? 
Yes exactly. Thanks a lot for your answer
