### ISSUE TITLE
Release notes: explain model limitations

### ISSUE THREAD

**Issue by dabinat** [mozilla/DeepSpeech#3059]
There are frequent posts on Discourse by people confused with the poor inference results they are getting on what they consider to be “easy” transcription tasks.

Currently the only explanation of the pre-trained model’s quality is its Librispeech score in the release notes. While this is useful for comparison between speech libraries, it is not necessarily a measure of real-world performance.

I feel that the release notes for 0.8 and future releases should mention the limitations of the model (i.e. not noise-robust, biased towards US male accents) so that people have a more realistic idea of what to expect.

**Comment by kdavis-mozilla** [comment]
Other than "not noise-robust, biased towards US male accents" what would you suggest the text include?

**Comment by dabinat** [comment]
@kdavis-mozilla How about something like this?

> Note that the pre-trained model is a work in progress and is not considered to be production-ready. The model currently performs best in low-noise environments with clear recordings and has a bias towards US male accents. It will likely need additional training to be ready for production use.

**Comment by kdavis-mozilla** [comment]
It's a reasonable first cut, but if your "production" environment is low-noise and used in the US, it is a production model. So I don't think this really captures what needs to be said.

**Comment by DanBmh** [comment]
I think you can see some of the limitations in a benchmark I did run. The benchmark doesn't test transcription accuracy directly, it's a test for speech-to-intent accuracy. So DeepSpeech is not the only factor, but the most important of it.
The low performance can be explained with "not noise-robust, biased towards US male accents", but I think a graph with comparison to other services is also helpful for first performance estimations.

![compare_barrista_extra](https://user-images.githubusercontent.com/18572490/84764370-e6967d00-afcd-11ea-9f8c-69f68ed58b97.png)

The [benchmark](https://github.com/Picovoice/speech-to-intent-benchmark) consists of 620 spoken commands of 50 different people (part of them with stronger accents) ordering coffee in english. A detection is correct if all important parts of the order (coffee type, size, sugar amount, ...) are extracted correctly (so it can fail if only one single word was misunderstood). It also tests the influence of background noise by mixing kitchen or cafe noises into the audio files.

You can see that plain DeepSpeech transcription (Free Speech) which uses 0.7 model and scorer doesn't work well, but the performance can be greatly improved if you use domain specific language models.
Short note: The Free Speech benchmark was run only with 1/6 of the files because of long runtimes, but in other tests this did only have a small effect to overall accuracy (~±0.03).

The complete benchmark code can be found [here](https://gitlab.com/Jaco-Assistant/Benchmark-Jaco).

**Comment by kdavis-mozilla** [comment]
In light of what I mentioned in my last comment, could you try again to capture what you want to be said in the release notes? Note that "production environment" is ill-defined, thus not a meaningful term to include in the text.

**Comment by dabinat** [comment]
@kdavis-mozilla Ok, here’s an updated version:

> Note that the pre-trained model is a work in progress. The model currently performs best in low-noise environments with clear recordings and has a bias towards US male accents. This does not mean the model cannot be used outside of these conditions, but that accuracy may be lower. Some users may need to train the model further to meet their intended use-case.

**Comment by kdavis-mozilla** [comment]
Added to draft release notes.
