### ISSUE TITLE
DeepSpeech does not build properly on alternative Linux systems (i.e. ARM).

### ISSUE THREAD

**Issue by sbluhm** [mozilla/DeepSpeech#3200]
I tried to build DeepSpeech 0.7.4 on a Rasperry Pi 3 running CentOS 8.

Instructions followed: https://github.com/mozilla/DeepSpeech/blob/v0.7.4/native_client/README.rst

By looking at the Makefile (definitions.mk), it does not consider the processor type when compiling for Linux systems. Linux systems are always assumed to be x86_64. This assumption is not valid.

Result: When building DeepSpeech 0.7.4, the Python bindings make fails and also creates the wrong architecture package.

1. A precompiled x86_64 version of SWIG is downloaded (not an ARM version in my case).
2. A x86_64 Python wheel file is created and cannot be installed on alternative architectures.

(I have compiled the latest SWIG 4.0.2 and updated the symbolic link in native_client/ds_swig/swig to point to the system version. That allowed me to get to 2.)
Python 3.6.8
Bazel 0.24.1 built from source.
gcc 8.3.1 Redhat Version 8.3.1-4

Expected implementation:
If Linux is detected, also check for processor type for the build flags. Using the mentioned cross-building flags will not work for on-system building.

**Comment by lissyx** [comment]
We only support cross compilation for ARM systems, but if you need you might be able to leverage TARGET make var, see definitions.mk

**Comment by lissyx** [comment]
> Result: When building DeepSpeech 0.7.4, the Python bindings make fails and also creates the wrong architecture package.

This should work if you pass `TARGET=rpi3` but in our case it does also assume cross-compilation.

And if you ask, we cannot really support native ARM builds because it'd require lots of CI extra hardware and complexity.

In your case, adapting cross compilation to target a centos 8 system should do the trick, but you might also have to adapt tensorflow build as well, i know they have had native build support but moved to cross compilation as well.

**Comment by lissyx** [comment]
That being said, i would have expected our prebuilt binaries for rpi3 to work on your centos given the versions. Can you elaborate why it does not work ?
