### ISSUE TITLE
Execution time measure within native client

### ISSUE THREAD

**Issue by lissyx** [mozilla/DeepSpeech#450]

**Comment by lissyx** [comment]
The idea was to provide a mean to get CPU execution time, with MFCC and inference granularity.

**Comment by Cwiiis** [comment]
Commented on IRC, but just repeating here - I think this code would be better off living entirely in the client (if it's needed). A consumer of libdeepspeech isn't always going to be interested in time spent in this code, and it's easily measurable without having to alter the library. Especially as timing code is very platform-specific, I don't think it's a good idea to have this code here.

If we are going to have this in the client, it would be good for it to be controlled by a command-line parameter too, otherwise it kills the ability to use the client easily in piped commands.
