### ISSUE TITLE
Improving Language Model

### ISSUE THREAD

**Issue by pdcoded** [mozilla/DeepSpeech#500]
Hey @kdavis-mozilla , I tried training this model on my dataset . Seems like language model is bottleneck. What all changes in LM do we expect to see in next few days ? Also can we implement word2vec to derive more semantic understanding of context? Right now, there is no intuitiveness to how the model corrects the words in test batch. Few output seem fuzzy.

2nd question . With the current language model, given that I train in on conversational telephonic data with not more than 7-8 sec clips, what all tuning can I do to the LM ? Should I decrease the beam width ?

**Comment by kdavis-mozilla** [comment]
The current language model in master is a place holder and it's slow as it's all on the CPU.

Over the next few weeks I'm going to try and tackle #408 #409 #400 and #410 

I hadn't planned on using word2vec but if you have some interesting ideas there feel free to open issue(s).

Right now the beam width is tuned to the memory of our training server, nothing more. It's very likely not optimal in any sense of the word. However, due to the upcoming work on #408 #409 #400 and #410 not a lot of effort was put in to tuning the beam width. 

One hint on making the beam width better is to only do WER reports on a model that is some what better trained. Then the corrections it does are less costly. 

In the next few weeks there will be much more work on the language model.

**Comment by kdavis-mozilla** [comment]
@pdcoded I'm going to close this as I think all associated questions were addressed

**Comment by pdcoded** [comment]
Sure :)
