### ISSUE TITLE
Purpose of test and dev sets

### ISSUE THREAD

**Issue by striki70** [mozilla/DeepSpeech#570]
What is the purpose of test and dev sets?
Will the learning process be affected if I use let's say only 1000 waves for test and dev sets?

**Comment by crs117** [comment]
I would recommend reading this book.

http://www-bcf.usc.edu/~gareth/ISL/ISLR%20Sixth%20Printing.pdf

I too am a newbie but I will try to explain and may get some of the terms incorrect.

You need multiple data sets in order for machine learning to build the model. Training sets are processed in order to build a model for testing. The testing data sets are there in order to test the model built from the training data sets in order to obtain the differential. This differential is used to alter the shape of the model to not map as directly to the training set. This is how it improves over each epoch. 

Changing the data sets will affect many factors. The basic concept is the more data you have to work with the better the machine learning will be. The amount of data in the training vs test sets will affect factors like over fitting and other ratios that may need to be adjusted in order to produce the best models.

**Comment by kdavis-mozilla** [comment]
@striki70 

- Training data sets are for the system to learn on. Consider it like being in university. Before a test in a course one reads the course's book and tries to learn everything possible from the book.
- Dev data sets are for the system to test and refine its knowledge on. Consider a professor giving you old tests from past years to validate your understanding on. The old tests are like the dev set. They are almost like the real test, but only for practice so you can better understand where you should study more.
- Test sets are, simply put, for the real test of the system. They are just like the real test you have to take in university.
