### ISSUE TITLE
Out of memory issue when --train_batch_size is 100

### ISSUE THREAD

**Issue by harrypotter90** [mozilla/DeepSpeech#606]
I get a Out of memory issue when i set **train_batchsize = 100**
```
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 4 Chunks of size 252137728 totalling 961.83MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:700] Sum Total of in-use chunks: 3.63GiB
I tensorflow/core/common_runtime/bfc_allocator.cc:702] Stats: 
Limit:                  3894804480
InUse:                  3894778368
MaxInUse:               3894803200
NumAllocs:                    7341
MaxAllocSize:            252137728

W tensorflow/core/common_runtime/bfc_allocator.cc:274] **********************************xx****************************************************************
W tensorflow/core/common_runtime/bfc_allocator.cc:275] Ran out of memory trying to allocate 193.0KiB.  See logs for memory state.
W tensorflow/core/framework/op_kernel.cc:993] Resource exhausted: OOM when allocating tensor with shape[100,494]
```

**Same command and dataset but when --train_batch_size= 1
It works all fine..**

```
D Sending Job (id: 56, worker: 0, epoch: 1, set_name: test)...
I Test of Epoch 1 - WER: 1.000000, loss: 142.373315187, mean edit distance: 0.936888
I --------------------------------------------------------------------------------
I WER: 1.000000, loss: 20.758251, mean edit distance: 1.000000
I  - src: "aaah"
I  - res: ""
I --------------------------------------------------------------------------------
I WER: 1.000000, loss: 21.429127, mean edit distance: 1.000000
I  - src: "aaah"
I  - res: ""
I --------------------------------------------------------------------------------
I WER: 1.000000, loss: 21.995270, mean edit distance: 1.000000
I  - src: "mmm"
I  - res: ""
I --------------------------------------------------------------------------------
I WER: 1.000000, loss: 22.327377, mean edit distance: 1.000000
I  - src: "mmm"
I  - res: ""
I --------------------------------------------------------------------------------
I WER: 1.000000, loss: 23.341921, mean edit distance: 1.000000
I  - src: "aaah"
I  - res: ""
I --------------------------------------------------------------------------------
I WER: 1.000000, loss: 23.498835, mean edit distance: 1.000000
I  - src: "aaah"
I  - res: ""
I --------------------------------------------------------------------------------
I WER: 1.000000, loss: 24.080647, mean edit distance: 1.000000
I  - src: "mmm"
I  - res: ""
I --------------------------------------------------------------------------------
I WER: 1.000000, loss: 24.106306, mean edit distance: 1.000000
I  - src: "aaah"
I  - res: ""
I --------------------------------------------------------------------------------
I WER: 1.000000, loss: 24.110025, mean edit distance: 1.000000
I  - src: "mmm"
I  - res: ""
I --------------------------------------------------------------------------------
I WER: 1.000000, loss: 24.185291, mean edit distance: 1.000000
I  - src: "mmm"
I  - res: ""
I --------------------------------------------------------------------------------
D Epochs - running: 1, done: 0
D Closing queues...
D Session closed.
```

Note that : Data set size is 90KB 

**Command i am using** : python -u DeepSpeech.py --train_files /home/english/files/english-test.csv --dev_files /home/english/files/english-test.csv --test_files /home/english/files/english-test.csv --train_batch_size 1 --dev_batch_size 1 --n_hidden 494 --test_batch_size 1 --log_level 0 --fulltrace True --epoch 1 --checkpoint_dir /root/.local/share/deepspeech/english2344

**Comment by harrypotter90** [comment]
I am sure, Experts here will be interested in Hardware configuration - 
6 cores CPU ; 128GB ram ; 8 GPUS (2cards) NVidia M40

**Comment by kdavis-mozilla** [comment]
You have to find a batch size that works for your hardware through, say, binary search.

For example, you know 100 doesn't work. Try 50. If that doesn't work, try 25. If that doesn't work, try 12. If that does work, try 18.... until you find that maximum value that does work.

**Comment by harrypotter90** [comment]
Sure, Thanks @kdavis-mozilla

**Comment by jackHuanghello** [comment]
When I set the train_batch_size to 12 and the n_hidden to 512, the GPU utilization is very low. Does someone have the problem with me?

**Comment by elpimous** [comment]
Try to use a highter value in batch size (highter value = better gpu usage)
Tested myself and confirmed !
If you can't, due to OOM errors, you don't have enough gpu ram ?! (2×4go)

**Comment by jackHuanghello** [comment]
But I when I try to use a higher value in batch size, the utilization of gpu become lowr.  I set "--n_hidden 512,  train_bathc_size 50". In the training procee, the gpu utilization will be 0% for a long time and then be 100% for a short time circularly. And It doesn't show any message about OOM errors.

**Comment by jackHuanghello** [comment]
This is my input command:
`./DeepSpeech.py --train_files ./data/CV/cv-valid-train.csv --dev_files ./data/CV/cv-valid-dev.csv --test_files ./data/CV/cv-valid-test.csv --export_dir ./export_model/ --validation_step 1 --display_step 1 --checkpoint_dir /disk2/hx-dir/IDE/deepspeech-venv/checkPoint512-50 --n_hidden 512 --trian_batch_size 50`

**Comment by elpimous** [comment]
Remove display step


Envoyé depuis mon smartphone Samsung Galaxy.
-------- Message d'origine --------De : jackHuanghello <notifications@github.com> Date : 28/12/2017  12:38  (GMT+01:00) À : mozilla/DeepSpeech <DeepSpeech@noreply.github.com> Cc : FOUCAULT Vincent <elpimous12@orange.fr>, Comment <comment@noreply.github.com> Objet : Re: [mozilla/DeepSpeech] Out of memory issue when --train_batch_size is 100 (#606) 
This is my input command:

./DeepSpeech.py --train_files ./data/CV/cv-valid-train.csv --dev_files ./data/CV/cv-valid-dev.csv --test_files ./data/CV/cv-valid-test.csv --export_dir ./export_model/ --validation_step 1 --display_step 1 --checkpoint_dir /disk2/hx-dir/IDE/deepspeech-venv/checkPoint512-50 --n_hidden 512 --trian_batch_size 50

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/mozilla/DeepSpeech","title":"mozilla/DeepSpeech","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/mozilla/DeepSpeech"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jackHuanghello in #606: This is my input command:\r\n`./DeepSpeech.py --train_files ./data/CV/cv-valid-train.csv --dev_files ./data/CV/cv-valid-dev.csv --test_files ./data/CV/cv-valid-test.csv --export_dir ./export_model/ --validation_step 1 --display_step 1 --checkpoint_dir /disk2/hx-dir/IDE/deepspeech-venv/checkPoint512-50 --n_hidden 512 --trian_batch_size 50`"}],"action":{"name":"View Issue","url":"https://github.com/mozilla/DeepSpeech/issues/606#issuecomment-354275297"}}}

**Comment by jackHuanghello** [comment]
Thank you! It really works!

**Comment by elpimous** [comment]
Happy for U.
