### ISSUE TITLE
Checkpoint is not resuming from left off point

### ISSUE THREAD

**Issue by pecastro** [mozilla/DeepSpeech#695]
9b7a6750ce71de02370e6a1783674e466a9de6ed from #537 seems to prevent the checkpoint functionality from working.

Subsequent runs of bin/run-ldc93s1.sh always start from scratch whereas reverting this commit restores the old funcitonality.

**Comment by andi4191** [comment]
@tilmankamp, @kdavis-mozilla : Root cause analyzed for this behavior, its the decoupling of the checkpoint_dir from the tf.train.MonitoredTrainingSession. It is required to pass the checkpoint_dir in this API too.

Will initiate the pull request for this shortly. Please suggest.

**Comment by tilmankamp** [comment]
@andi4191 Indeed a very strange behavior of the API - I'd consider looking into the implementation.

**Comment by andi4191** [comment]
@tilmankamp : I checked the code from tensor flow API

** if checkpoint_dir:
    all_hooks.append(basic_session_run_hooks.StepCounterHook(
        output_dir=checkpoint_dir, every_n_steps=log_step_count_steps))

    if (save_summaries_steps and save_summaries_steps > 0) or (
        save_summaries_secs and save_summaries_secs > 0):
      all_hooks.append(basic_session_run_hooks.SummarySaverHook(
          scaffold=scaffold,
          save_steps=save_summaries_steps,
          save_secs=save_summaries_secs,
          output_dir=checkpoint_dir))
    if save_checkpoint_secs and save_checkpoint_secs > 0:
      all_hooks.append(basic_session_run_hooks.CheckpointSaverHook(
          checkpoint_dir, save_secs=save_checkpoint_secs, scaffold=scaffold))

  if hooks:
    all_hooks.extend(hooks)
  return MonitoredSession(session_creator=session_creator, hooks=all_hooks,
                          stop_grace_period_secs=stop_grace_period_secs)**

It appears that if checkpoint_dir is mentioned it creates another StepCounterHook which counts steps per seconds whereas if we pass save_checkpoint_secs then it creates another CheckpointSaverHook.

If I just pass the checkpoint_dir and no save_checkpoint_secs in MonitoredTrainingSession it is still resuming the epoch count from there on. I am not really sure how StepCounterHook is influencing the checkpointing alone because from the StepCounterHook code it appears to be dealing with summary alone in all of its member functions.

PS: This issue appears to be a blocker now.

**Comment by tilmankamp** [comment]
Is everything fine, if we keep passing `save_checkpoint_secs` and `checkpoint_dir` into `MonitoredTrainingSession`?

**Comment by andi4191** [comment]
@tilmankamp : Yes, it is working fine with those changes. Verified the max_to_keep functionality as well.

**Comment by kdavis-mozilla** [comment]
@andi4191 I'd guess it'd be best for you to initiate a PR for this.
