### ISSUE TITLE
Model Parallelism 

### ISSUE THREAD

**Issue by jongsae** [mozilla/DeepSpeech#739]
Hi all, just a quick question. 

run-cluster.sh + DeepSpeech.py seem to only cover data-parallelism implementation and model parallelism implementation described in the paper does not exist as of now. Do you have plans for developing this feature? 

I was about to modify the code and develop this feature on my own but wanted to check if the feature already exists or is being developed before moving on.

**Comment by kdavis-mozilla** [comment]
We have no plans for implementing model parallelism. Are you referring to? The model parallelism of the bi-directional layers?

**Comment by jongsae** [comment]
Yup exactly. I also noticed that Deep Speech 2 paper does not seem to discuss the model parallelism. Is there a reason why the model parallelism is not considered?

**Comment by kdavis-mozilla** [comment]
I'd guess for Deep Speech they simply didn't have enough GPU TFLOPs on a single GPU to train on the large data sets due to the bi-directional layers being very computationally intensive. So, they split the forward+backward RNN of the bi-directional layers across GPU's.

Deep Speech 2 is less computationally demanding and created later when, I'd guess, they had more GPU TFLOPs at their disposal.

**Comment by jongsae** [comment]
@kdavis-mozilla Thanks for clarification!

**Comment by lissyx** [comment]
Looks like that was an answered question.
