### ISSUE TITLE
Deepspeech slow/wedged on preparation of large data sets -- mfcc computation? 

### ISSUE THREAD

**Issue by gvoysey** [mozilla/DeepSpeech#930]
I am training on TEDLIUM + LibriSpeech + a small custom data set.  Data sets imported cleanly.

I am getting warnings of the form `WARNING:root:frame length (1103) is greater than FFT size (512), frame will be truncated. Increase NFFT to avoid.`  during training -- a few hundred times per epoch. 

I believe this is from the LibriSpeech data.  Should I be concerned that MFCCs are not being properly extracted and that the training may go wrong as a result?

**Comment by kdavis-mozilla** [comment]
How did you determine this was from the LibriSpeech data?

**Comment by gvoysey** [comment]
I don't recall seeing those warnings appear when I trained on my custom data  or TEDLIUM separately. 

Either way, it would be good to ensure that they don't reflect aliasing or clipping on MFCC extraction.  

Probably not related, but have you experienced much slower training times with librispeech than with other datasets?  I was able to train tedlium in ~ 18 hours over 25 epochs, but librispeech alone was taking roughly 18 hours _per epoch_, and combined is slower still.   I'm training on 16 cores and 2 titans.

**Comment by kdavis-mozilla** [comment]
I ask because we train often on LibriSpeech and never see such warnings. I'm curious as to what's different on your side.

LibriSpeech is about 1000 hours TED about 200 hours. So a factor of 5 would be about normal. But what you're seeing is more than just that. Have you tried to increase the batch size? On our Titan X Pascal', 12GB per card, we could get it up to 12 for LibriSpeech.
