### ISSUE TITLE
Extra tower scope created by validation code

### ISSUE THREAD

**Issue by kdavis-mozilla** [mozilla/DeepSpeech#94]
The code
```python
validation_tower_decodings, validation_tower_labels = decode_batch(data_sets.dev)
```
creates an extra tower scope.

For example on my laptop with a single GPU and no CPU the code creates a graph with the scopes `tower_0` and `tower_0_1`. The scope `tower_0` is expected and should be there. The scope `tower_0_1` is extra and should not be there.

If one takes out the line above, the scope `tower_0_1` no longer appears. One can see these scopes by using tensorboard. (I've not checked, but I would guess that for the multiple GPU case each GPU's tower is doubled.)

@tilmankamp I think this implies that the validation code will have to be changed.

**Comment by tilmankamp** [comment]
This was indeed expected and intended, as the validation step required the construction of another graph to fetch (resulting in calls to ```batch_set.next_batch()``` on the validation set instead of the train set). The alternative approach would be the classic ```feed_dict``` one with the aforementioned performance problems. 
Why is having a second scope a problem? The two scopes should share all model variables.

**Comment by kdavis-mozilla** [comment]
I think you're right. I was thinking of the scope not as an operator scope but as a variable scope.
