### ISSUE TITLE
Add documentation on GPU vs CPU speed

### ISSUE THREAD

**Issue by kdavis-mozilla** [mozilla/DeepSpeech#993]

**Comment by kdavis-mozilla** [comment]
Fixed but we need to wait until PyPI increases our limit on deepspeech-gpu before merging

**Comment by mbebenita** [comment]
When I tried using a GPU I noticed it was actually quite a bit slower than the CPU version. which was surprising at first. This was primarily due to  initialization time and didn't reflect the actual time it took to do the inference (which was quite fast). We should print out the various initialization steps and the time it takes to do the inference.

**Comment by lissyx** [comment]
@mbebenita We do have some of that on the `C++` DeepSpeech binary if you toggle the `-t` flag when running it. It would at least cover the inference itself and `MFCC` computation, though, not the loading of the file itself.

**Comment by mbebenita** [comment]
@lissyx I'm mostly concerned with what we print in the example python commands we share with users. They will most likely do the inference for a single audio clip and walk away thinking the inference is slow, and I want to avoid that.

**Comment by lissyx** [comment]
It's being addressed by PR #1011
